post https://safe-plateau-98676.herokuapp.com/api/contacts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI....

{
  "name": "Liisa Hirvi",
  "address": "Hirvikatu 7 b 34, Espoo",
  "email":"liisa@gmail.com",
  "userId":"5d7565ff66055a0004c6f3ac"
}